#!/system/bin/sh
clear
cd ${0%/*}

# define color
normal="\033[0m"
green="\033[0;32m"
red="\033[91m"

# busybox dir
busybox="/data/adb/magisk/busybox"
mihomo="mihomo"
mode="tun" # tun or tproxy
file_name="ssc.yaml"

# Array storage area
package_list=(
com.azure.authenticator
com.android.email
com.ss.android.article.lite
com.eg.android.AlipayGphone
com.tencent.mm
com.tencent.mobileqq
com.MobileTicket
com.alibaba.android.rimet
com.epoint.mobileframenew.zj.chongqing
com.autonavi.minimap
com.cebbank.mobile.cemb
cmb.pb
com.jingdong.app.mall
)
cidrs=(
  0.0.0.0/8
  10.0.0.0/8
  100.64.0.0/10
  127.0.0.0/8
  169.254.0.0/16
  172.16.0.0/12
  192.0.0.0/24
  192.0.2.0/24
  192.88.99.0/24
  192.168.0.0/16
  198.51.100.0/24
  203.0.113.0/24
  224.0.0.0/4
  240.0.0.0/4
  255.0.0.0/4
  255.255.255.255/32
)
cidrs6=(
  ::/128
  ::1/128
  ::ffff:0:0/96
  100::/64
  64:ff9b::/96
  2001::/32
  2001:10::/28
  2001:20::/28
  2001:db8::/32
  2002::/16
  fc00::/7
  fe80::/10
  ff00::/8
  2408:8000::/20
  2409:8000::/20
  240a:4000::/21
  240e::/20
)
# create an array of uids
Black_List() {
for package_name in ${package_list[@]}; do
    # uids=$(dumpsys package "$package_name" 2>/dev/null | grep 'userId' | cut -d '=' -f2) # others
    # uids=$(dumpsys package "$package_name" 2>/dev/null | grep 'appId' | cut -d '=' -f2) #oneplus
    uids=$(grep $package_name /data/system/packages.list | cut -d " " -f2) # first choice
    if [ -n "$uids" ]; then # Prevent empty values in arrays
    black_uid+=("$uids")
    fi
    format="%-33s %-8s\n"
    printf "$format" $package_name: $uids 
done
}
# define startup
Start_Proxy() {
  if [ -f "${0%/*}/${mihomo}" ]; then
    chmod 755 ${0%/*}/${mihomo} 
    chown root:root ${0%/*}/${mihomo}
    ulimit -SHn 1000000
    ${busybox} setuidgid 0:20333 ./${mihomo} -f ${0%/*}/data/${file_name} -d ${0%/*}/data/ > /dev/null 2>&1 &
  fi
}
# Environment initialization
initialize() {
  PID=$(pidof ${mihomo})
  if pidof ${mihomo} > /dev/null 2>&1;then
      kill -15 $PID > /dev/null 2>&1 
  fi
    Erase_Tproxy
    echo -e "${red}环境初始化完成${normal}"
}
# create Create_Tproxy erase Erase_Tproxy
create() {
  # ===PREROUTING===
	$1 ru a fwmark 1 table $2
	$1 ro a local $3 dev lo table $2
	$4 -t mangle -N $5
	for cidr in $6; do
		$4 -t mangle -A $5 -d ${cidr} -j RETURN
		echo -e "PREROUTING ${green}$5${normal} -d ${cidr} -j RETURN"
	done
	$4 -t mangle -A $5 -p tcp -j TPROXY --on-port ${port} --tproxy-mark 1
	$4 -t mangle -A $5 -p udp -j TPROXY --on-port ${port} --tproxy-mark 1
	$4 -t mangle -A PREROUTING -j $5
	# =====OUTPUT=====
	$4 -t mangle -N ${5}_MASK
	for puid in ${7}; do
    $4 -t mangle -A ${5}_MASK -m owner --uid-owner ${puid} -j RETURN
    echo -e "OUTPUT ${green}${5}_MASK${normal} -m owner --uid-owner ${puid} -j RETURN"
  done
	$4 -t mangle -A ${5}_MASK -m owner --gid-owner 20333 -j RETURN
	  echo -e "OUTPUT ${red}${5}_MASK -m owner --gid-owner 20333 -j RETURN${normal}"
	for cidr in ${6}; do
		$4 -t mangle -A ${5}_MASK -d ${cidr} -j RETURN
		echo -e "OUTPUT ${green}${5}_MASK${normal} -d ${cidr} -j RETURN"
	done
	$4 -t mangle -A ${5}_MASK -j MARK --set-mark 1
	$4 -t mangle -A OUTPUT -p tcp -j ${5}_MASK
	$4 -t mangle -A OUTPUT -p udp -j ${5}_MASK
} 
Create_Tproxy() {
  Black_List
	create ip 100 0.0.0.0/0 iptables TProxy "${cidrs[*]}" "${black_uid[*]}"
	create "ip -6" 106 ::/0 ip6tables TProxy6 "${cidrs6[*]}" "${black_uid[*]}"
}
# Erase_Tproxy
erase() {
	$1 ru d fwmark 1 table $2
	$1 ro d local $3 dev lo table $2
	${4}-save | grep TProxy | grep "\-A" | sed 's/-A/'${4}' -t mangle -D/g' | sh
	$4 -t mangle -X $5
	$4 -t mangle -X ${5}_MASK
}
Erase_Tproxy() {
  if iptables-save | grep "TProxy" > /dev/null ; then
  	erase ip 100 0.0.0.0/0 iptables TProxy
  	erase "ip -6" 106 ::/0 ip6tables TProxy6
  fi
}
# Setting modes can be created regardless of the original profile proxy mode.
change2tun() {
Black_List
black_uids=$(IFS=","; echo "${black_uid[*]}")
sed -i "s|^tproxy-port:.*|tun: { enable: true, stack: system, dns-hijack: [\"any:53\"], auto-route: true, auto-detect-interface: true, device: tun0, exclude-uid: [${black_uids}] }|" ./data/${file_name}
sed -i "s|^tun:.*|tun: { enable: true, stack: system, dns-hijack: [\"any:53\"], auto-route: true, auto-detect-interface: true, device: tun0, exclude-uid: [${black_uids}] }|" ./data/${file_name}
}

change2tproxy() {
    port="10810"
    sed -i "s|^tun:.*|tproxy-port: ${port}|" ./data/${file_name}
    sed -i "s|^tproxy-port:.*|tproxy-port: ${port}|" ./data/${file_name}
# Assign a value to port for iptables 
    # [ -f ${0%/*}/data/${file_name} ] && port=$(grep 'tproxy-port:' ${0%/*}/data/${file_name} | cut -d ':' -f2 | tr -d ' ') 
}

# work chain 
run() {
initialize # 初始化
if [ $mode = "tproxy" ]; then # There must be spaces on both sides of the equal sign
  change2tproxy
  Create_Tproxy
elif [ $mode = "tun" ]; then
  change2tun
fi
Start_Proxy
}

stop() {
initialize # 关闭$mihomo
}